server:
  port: 20000
  servlet:
    encoding:
      force: true
      charset: UTF-8
spring:
  mail:
    username: 1069306849@qq.com
    host: smtp.qq.com
    port: 465
    protocol: smtps
    password: lttldcnuysssbeea
    default-encoding: UTF-8
  jmx:
    default-domain: huhuiyu.teach.service
  web: 
    resources:
      add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    default-property-inclusion: non-null
    serialization:
      write-dates-as-timestamps: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 50MB
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://shuailanjun.top:3306/db_teach_service?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: test
    password: User4-test
    hikari:
      connection-test-query: select 1
      max-lifetime: 60000
mybatis:
  config-location: classpath:mybatis-config.xml
pagehelper:
  reasonable: true